# Generated by Django 5.1.1 on 2024-10-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='salary',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
